In [1]:
import pandas as pd

In [2]:
movie=pd.read_csv("movies_small.csv")
rate=pd.read_csv("ratings.csv")

In [3]:
import re
def movies(name):
    name=name.split("(")[0]
    return name.lower()
movie["title"]=movie["title"].apply(movies)

In [4]:
movie.head(2)

   movieId       title                                       genres
0        1  toy story   Adventure|Animation|Children|Comedy|Fantasy
1        2    jumanji                    Adventure|Children|Fantasy

In [5]:
data=rate.pivot(index="movieId",columns="userId",values="rating").fillna(0)

In [6]:
data

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
movieId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,0.0,0.0,4.0,0.0,4.5,0.0,0.0,0.0,...,4.0,0.0,4.0,3.0,4.0,2.5,4.0,2.5,3.0,5.0
2,0.0,0.0,0.0,0.0,0.0,4.0,0.0,4.0,0.0,0.0,...,0.0,4.0,0.0,5.0,3.5,0.0,0.0,2.0,0.0,0.0
3,4.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193581,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
193583,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
193585,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
193587,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
193609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
movie_rated=rate.groupby("userId")["rating"].count()
user_rate=rate.groupby("movieId")["rating"].count()

In [8]:
data=data.loc[user_rate[user_rate>10].index]
data=data.loc[:,movie_rated[movie_rated>50].index]

In [9]:
data

userId,1,4,6,7,10,11,15,16,17,18,...,600,601,602,603,604,605,606,607,608,610
movieId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,0.0,4.5,0.0,0.0,2.5,0.0,4.5,3.5,...,2.5,4.0,0.0,4.0,3.0,4.0,2.5,4.0,2.5,5.0
2,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,...,4.0,0.0,4.0,0.0,5.0,3.5,0.0,0.0,2.0,0.0
3,4.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
5,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.5,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
6,4.0,0.0,4.0,0.0,0.0,5.0,0.0,0.0,0.0,4.0,...,0.0,0.0,3.0,4.0,3.0,0.0,0.0,0.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174055,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
176371,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
177765,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
179819,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
187593,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
from scipy.sparse import csr_matrix
data.reset_index(inplace=True)
sparce=csr_matrix(data)
print(sparce)

  (0, 0)	1.0
  (0, 1)	4.0
  (0, 4)	4.5
  (0, 7)	2.5
  (0, 9)	4.5
  (0, 10)	3.5
  (0, 11)	4.0
  (0, 13)	3.5
  (0, 17)	3.0
  (0, 20)	3.0
  (0, 21)	3.0
  (0, 26)	5.0
  (0, 29)	5.0
  (0, 30)	4.0
  (0, 32)	3.0
  (0, 35)	5.0
  (0, 39)	5.0
  (0, 40)	4.0
  (0, 41)	4.0
  (0, 42)	2.5
  (0, 44)	4.5
  (0, 47)	0.5
  (0, 48)	4.0
  (0, 51)	2.5
  (0, 54)	4.0
  :	:
  (2118, 358)	4.0
  (2118, 370)	4.5
  (2119, 0)	179819.0
  (2119, 38)	3.5
  (2119, 63)	3.0
  (2119, 99)	0.5
  (2119, 128)	4.5
  (2119, 157)	4.5
  (2119, 237)	0.5
  (2119, 257)	4.5
  (2119, 318)	2.0
  (2119, 346)	2.0
  (2119, 358)	5.0
  (2119, 366)	3.5
  (2120, 0)	187593.0
  (2120, 38)	4.0
  (2120, 63)	5.0
  (2120, 147)	2.5
  (2120, 156)	4.5
  (2120, 157)	5.0
  (2120, 187)	5.0
  (2120, 206)	4.0
  (2120, 237)	3.0
  (2120, 318)	3.5
  (2120, 358)	4.0

In [12]:
from sklearn.neighbors import NearestNeighbors
knn=NearestNeighbors(metric="cosine",algorithm="brute",n_neighbors=20)
knn.fit(sparce)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=20)

In [120]:
from difflib import get_close_matches
def app(name):
    try:
        list_of_movies=movie["title"].to_list()
        matching=get_close_matches(name,list_of_movies,n=1, cutoff=0.6)[0]
        
        movie_id = movie[movie["title"] == matching]["movieId"].values[0]
        pivot_index = data[data["movieId"] == movie_id].index[0]
            
        distance,indice=knn.kneighbors(sparce[pivot_index],n_neighbors=11)
        zipped=zip(indice.squeeze().tolist(), distance.squeeze().tolist())    
        sorted_movie=sorted(zipped,key=lambda x:x[1],reverse=False)[1:]
        
        lista=[]
        for idc,dist in sorted_movie:
            x=data.iloc[idc]["movieId"]
            title = movie[movie["movieId"] == x]["title"].values[0]
            lista.append(title)
        return lista
    except:
        return f'{name} was not found'

In [134]:
app("hacker")

['demolition man ',
 'hot shots! part deux ',
 'beverly hills cop iii ',
 "city slickers ii: the legend of curly's gold ",
 'timecop ',
 'tank girl ',
 'robin hood: men in tights ',
 'mars attacks! ',
 'major payne ',
 'village of the damned ']